// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zriqqxdjptrszsbbvnup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyaXFxeGRqcHRyc3pzYmJ2bnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzM5ODMsImV4cCI6MjA3MjU0OTk4M30.catuJDSXEm5mHPjPWq6xQBw40k_SjpHiFtRVz4WsbKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});